title: Richard Thomas
description: >- # this means to ignore newlines until "baseurl:"
  Tag line or contact details tbc
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-theme-minimal

show_downloads: false
# logo: /assets/images/index/rider.jpg

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
